/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Utemterv.java
 *
 * Created on 2010.01.31., 21:36:47
 */
package onyx;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.WindowConstants;

/**
 *
 * @author PIRI
 */
public class Utemterv extends javax.swing.JPanel implements ActionListener {
    JFrame frame;
    DatePicker dp;
    private String[] selecteddates;
    /** Creates new form Utemterv */
    public Utemterv() {
        initComponents();
    }

    public void disposeDatePicker(){
        if(dp.isValidSelection()){
            selecteddates=dp.getSelectedDates();
//            System.out.println(selecteddates);
        }
        frame.dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDatum = new javax.swing.JButton();

        btnDatum.setText("Dátum");
        btnDatum.setActionCommand("datum");
        btnDatum.addActionListener(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDatum)
                .addContainerGap(718, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDatum)
                .addContainerGap(476, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDatum;
    // End of variables declaration//GEN-END:variables

    public void actionPerformed(ActionEvent e) {
        if (e.getActionCommand().equals("datum")) {
            frame=new JFrame();
            frame.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
            dp=new DatePicker();
            dp.addComponentListener(Main.foablak);
            
            frame.add(dp);
            frame.validate();
            frame.pack();
            frame.setVisible(true);

        }
    }

   
}
